### ISSUE TITLE
How does it compare to nix?

### ISSUE THREAD

**Issue by trusktr** [Perlence/steeve#3]
The nix package manager (http://nixos.org) achieves a similar thing, allowing any number of versions of the same software to exist on the system at the same time. How does it compare to ~~stow~~steeve?

**Comment by Perlence** [comment]
I use steeve to manage manually built programs and downloaded binaries. I just follow the build instructions in the README of a program, manually install the dependencies via some package manager like dpkg or brew, build the program, and then use steeve to put the program into `/usr/local`.

I think Nix is great if you spend some time learning it. The curve may be steep. It's possible to achieve what I described with Nix, but it would take more time in the short term to write the derivation. On the other hand, once you've done it, you have the whole process of the build described, and you can reproduce it later more easily.

So, if you just have to build and install something quickly and you don't know Nix, steeve is an adequate solution.

**Comment by trusktr** [comment]
That's a great explanation. Thanks!
